[build]
  # Change this to 'frontend' to match your new GitHub folder name
  base = "frontend"
  command = "npm run build"
  # This tells Netlify to look for the 'dist' folder INSIDE 'frontend'
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 